services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_songapi
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Politecnica1
      - MSSQL_PID=Express
    ports:
      - "14490:1433"
    volumes:
      - ./init-sqlserver.sql:/init-sqlserver.sql:ro

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: ["/bin/bash", "-c", "for i in {1..30}; do /opt/mssql-tools/bin/sqlcmd -S sqlserver_songapi -U sa -P Politecnica1 -Q 'SELECT 1' && break; echo 'Esperando a que SQL Server acepte conexiones...'; sleep 3; done; /opt/mssql-tools/bin/sqlcmd -S sqlserver_songapi -U sa -P Politecnica1 -i /init-sqlserver.sql"]
    volumes:
      - ./init-sqlserver.sql:/init-sqlserver.sql:ro

  songapi:
    build: .
    container_name: songapi
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=BDD_PoliMusic_Song;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=usr_polimusic_gr2
      - SPRING_DATASOURCE_PASSWORD=Politecnica1
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: on-failure 